// src/pages/Checkout.tsx
import { useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { format } from "date-fns";
import { ArrowLeft, CheckCircle2, CreditCard, Lock, ShieldCheck } from "lucide-react";
import PageShell from "@/components/layout/PageShell";
import Seo from "@/components/Seo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getDoctor } from "@/data/doctors";
import { useBookings } from "@/hooks/useBookings";
import { toast } from "sonner";

const Checkout = () => {
  const { id = "" } = useParams();
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const doctor = getDoctor(id);
  const { add } = useBookings();

  const dateISO = params.get("date") || new Date().toISOString();
  const time = params.get("time") || "10:30";
  const date = new Date(dateISO);

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [card, setCard] = useState("");
  const [done, setDone] = useState(false);

  if (!doctor) {
    return (
      <PageShell>
        <div className="container py-32 text-center">
          <h1 className="font-display text-4xl">Specialist not found</h1>
        </div>
      </PageShell>
    );
  }

  const submit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || !email) {
      toast.error("Please complete your details.");
      return;
    }
    add({
      doctorId: doctor.id,
      doctorName: doctor.name,
      specialty: doctor.specialty,
      date: date.toISOString(),
      time,
      patient: name,
      price: doctor.price,
    });
    setDone(true);
    toast.success("Appointment confirmed.");
  };

  if (done) {
    return (
      <PageShell>
        <Seo title="Confirmed — BookEase" description="Your appointment is confirmed." />
        <section className="container py-32 text-center max-w-xl">
          <div className="mx-auto h-16 w-16 rounded-full bg-primary/10 flex items-center justify-center animate-scale-in">
            <CheckCircle2 className="h-8 w-8 text-primary" />
          </div>
          <h1 className="font-display text-5xl mt-8 animate-fade-in-up">Confirmed.</h1>
          <p className="mt-4 text-muted-foreground animate-fade-in-up [animation-delay:120ms]">
            A gentle reminder will be sent before your visit with {doctor.name} on {format(date, "EEEE, MMMM d")} at {time}.
          </p>
          <div className="mt-10 flex justify-center gap-4 animate-fade-in-up [animation-delay:240ms]">
            <Button onClick={() => navigate("/dashboard")} size="lg" className="rounded-full px-8">View my bookings</Button>
            <Button onClick={() => navigate("/search")} variant="outline" size="lg" className="rounded-full px-8">Browse more</Button>
          </div>
        </section>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <Seo title={`Checkout — ${doctor.name} | BookEase`} description="Confirm your appointment." />

      <div className="container pt-10">
        <Link to={`/service/${doctor.id}`} className="inline-flex items-center gap-2 text-sm text-muted-foreground story-link">
          <ArrowLeft className="h-3 w-3" /> Back to specialist
        </Link>
      </div>

      <section className="container grid lg:grid-cols-12 gap-12 py-16">
        <form onSubmit={submit} className="lg:col-span-7 space-y-10 animate-fade-in-up">
          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">Step 01</p>
            <h1 className="font-display text-5xl mt-3">Your details</h1>
          </div>

          <div className="grid sm:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="name">Full name</Label>
              <Input id="name" value={name} onChange={(e) => setName(e.target.value)} className="h-12 bg-card" placeholder="Amelia Doe" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12 bg-card" placeholder="amelia@email.com" />
            </div>
          </div>

          <div>
            <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">Step 02</p>
            <h2 className="font-display text-3xl mt-3">Payment</h2>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="card">Card number</Label>
              <div className="relative">
                <CreditCard className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input id="card" value={card} onChange={(e) => setCard(e.target.value)} className="h-12 pl-11 bg-card" placeholder="4242 4242 4242 4242" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Input className="h-12 bg-card" placeholder="MM / YY" />
              <Input className="h-12 bg-card" placeholder="CVC" />
            </div>
          </div>

          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Lock className="h-3 w-3" />
            Encrypted, never stored. Demo only.
          </div>

          <Button type="submit" size="lg" className="rounded-full px-10 h-12 w-full md:w-auto">
            Confirm appointment · €{doctor.price}
          </Button>
        </form>

        <aside className="lg:col-span-5 animate-fade-in-up [animation-delay:120ms]">
          <div className="sticky top-24 rounded-sm border border-border bg-card p-8 shadow-soft">
            <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">Summary</p>
            <div className="mt-6 flex items-center gap-4">
              <img src={doctor.image} alt={doctor.name} className="h-16 w-16 rounded-sm object-cover" />
              <div>
                <div className="font-display text-xl">{doctor.name}</div>
                <div className="text-sm text-muted-foreground">{doctor.specialty} · {doctor.city}</div>
              </div>
            </div>

            <dl className="mt-8 space-y-3 text-sm">
              <Row k="Date" v={format(date, "EEEE, MMMM d, yyyy")} />
              <Row k="Time" v={time} />
              <Row k="Clinic" v={doctor.clinic} />
              <Row k="Duration" v="30 min" />
            </dl>

            <div className="border-t border-border mt-6 pt-6 space-y-2 text-sm">
              <Row k="Consultation" v={`€${doctor.price}`} />
              <Row k="Booking fee" v="Included" />
            </div>
            <div className="border-t border-border mt-6 pt-6 flex items-end justify-between">
              <span className="text-xs uppercase tracking-widest text-muted-foreground">Total</span>
              <span className="font-display text-3xl">€{doctor.price}</span>
            </div>

            <div className="mt-6 flex items-center gap-2 text-xs text-muted-foreground">
              <ShieldCheck className="h-3 w-3 text-primary" /> Free cancellation up to 24h before.
            </div>
          </div>
        </aside>
      </section>
    </PageShell>
  );
};

const Row = ({ k, v }: { k: string; v: string }) => (
  <div className="flex items-center justify-between">
    <dt className="text-muted-foreground">{k}</dt>
    <dd>{v}</dd>
  </div>
);

export default Checkout;

// app/pages/service/[id]/checkout.vue
<script setup lang="ts">
import { format } from "date-fns";
import { getDoctor } from "~/data/doctors";
import { useBookingsStore } from "~/stores/bookings";

const route = useRoute();
const router = useRouter();
const bookingsStore = useBookingsStore();
onMounted(() => bookingsStore.load());

const doctor = computed(() => getDoctor(String(route.params.id)));
const dateISO = computed(() => String(route.query.date ?? new Date().toISOString()));
const time = computed(() => String(route.query.time ?? "10:30"));
const appointmentDate = computed(() => new Date(dateISO.value));
const name = ref("");
const email = ref("");
const card = ref("");
const done = ref(false);

const submit = () => {
  if (!doctor.value || !name.value || !email.value) return;
  bookingsStore.add({
    doctorId: doctor.value.id,
    doctorName: doctor.value.name,
    specialty: doctor.value.specialty,
    date: appointmentDate.value.toISOString(),
    time: time.value,
    patient: name.value,
    price: doctor.value.price
  });
  done.value = true;
};
</script>

<template>
  <section v-if="doctor && done" class="container py-20 sm:py-32 text-center max-w-xl">
    <h1 class="font-display text-4xl sm:text-5xl">Confirmed.</h1>
    <p class="mt-4 text-muted-foreground">A gentle reminder will be sent before your visit with {{ doctor.name }} on {{ format(appointmentDate, "EEEE, MMMM d") }} at {{ time }}.</p>
  </section>
  <section v-else-if="doctor" class="container grid lg:grid-cols-12 gap-8 sm:gap-12 py-12 sm:py-16">
    <form class="lg:col-span-7 space-y-5 sm:space-y-6 order-2 lg:order-1" @submit.prevent="submit">
      <h1 class="font-display text-4xl sm:text-5xl">Your details</h1>
      <input v-model="name" class="h-12 bg-card w-full rounded-sm border border-border px-3" placeholder="Full name" />
      <input v-model="email" type="email" class="h-12 bg-card w-full rounded-sm border border-border px-3" placeholder="Email" />
      <input v-model="card" class="h-12 bg-card w-full rounded-sm border border-border px-3" placeholder="Card number" />
      <button class="rounded-full px-8 sm:px-10 h-12 bg-primary text-primary-foreground w-full sm:w-auto">Confirm appointment · €{{ doctor.price }}</button>
    </form>
    <aside class="lg:col-span-5 order-1 lg:order-2">
      <div class="rounded-sm border border-border bg-card p-5 sm:p-8">
        <p class="text-xs uppercase tracking-[0.25em] text-muted-foreground">Summary</p>
        <div class="mt-3">{{ doctor.name }} · {{ doctor.specialty }}</div>
      </div>
    </aside>
  </section>
</template>
